export const CHART_COLOR_SETTINGS = {

    line:
    {
        backgroundColor: 0.2,
        borderWidth: 3,
        borderColor: 1,
        borderCapStyle: 1,
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 1,
        pointBackgroundColor: 1,
        pointBorderWidth: 1,
        pointRadius: 3,
        pointHoverRadius: 1,
        pointHitRadius: 1,
        pointHoverBackgroundColor: 1,
        pointHoverBorderColor: 0.1,
        pointHoverBorderWidth: 1,
        pointStyle: 1,
        hoverBackgroundColor: 1,
        hoverBorderColor: 1,
        hoverBorderWidth: 1,
    },

    bar:
    {
        backgroundColor: 1,
        borderWidth: 1,
        borderColor: 1,
        borderCapStyle: 1,
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 1,
        pointBackgroundColor: 1,
        pointBorderWidth: 1,
        pointRadius: 1,
        pointHoverRadius: 1,
        pointHitRadius: 1,
        pointHoverBackgroundColor: 1,
        pointHoverBorderColor: 1,
        pointHoverBorderWidth: 1,
        pointStyle: 1,
        hoverBackgroundColor: 0.8,
        hoverBorderColor: 1,
        hoverBorderWidth: 1,
    },
    pie:
    {
        backgroundColor: 0.6,
        borderWidth: 2,
        borderColor: 1,
        borderCapStyle: 1,
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 1,
        pointBackgroundColor: 1,
        pointBorderWidth: 1,
        pointRadius: 1,
        pointHoverRadius: 1,
        pointHitRadius: 1,
        pointHoverBackgroundColor: 1,
        pointHoverBorderColor: 1,
        pointHoverBorderWidth: 1,
        pointStyle: 1,
        hoverBackgroundColor: 1,
        hoverBorderColor: 1,
        hoverBorderWidth: 1,
    },
    scatter:
    {
        backgroundColor: 0.6,
        borderWidth: 2,
        borderColor: 1,
        borderCapStyle: 1,
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 1,
        pointBackgroundColor: 1,
        pointBorderWidth: 1,
        pointRadius: 1,
        pointHoverRadius: 1,
        pointHitRadius: 1,
        pointHoverBackgroundColor: 1,
        pointHoverBorderColor: 1,
        pointHoverBorderWidth: 1,
        pointStyle: 1,
        hoverBackgroundColor: 1,
        hoverBorderColor: 1,
        hoverBorderWidth: 1,
    },
    doughnut:
    {
        backgroundColor: 0.6,
        borderWidth: 2,
        borderColor: 1,
        borderCapStyle: 1,
        borderDash: [],
        borderDashOffset: 0.0,
        borderJoinStyle: 'miter',
        pointBorderColor: 1,
        pointBackgroundColor: 1,
        pointBorderWidth: 1,
        pointRadius: 1,
        pointHoverRadius: 1,
        pointHitRadius: 1,
        pointHoverBackgroundColor: 1,
        pointHoverBorderColor: 1,
        pointHoverBorderWidth: 1,
        pointStyle: 1,
        hoverBackgroundColor: 1,
        hoverBorderColor: 1,
        hoverBorderWidth: 1,
    },
}